### PR TITLE
Create Ceph directory when missing

### PR DESCRIPTION
**Pull request by git-harry**
Fix monitoring and add additional metrics/alarms

### CODE REVIEW

**Comment by hughsaunders** [comment]
:+1:

**Comment by mattt416** [comment]
Not related to this change specifically, but should we be ensuring /etc/ceph/ceph.client.raxmon.keyring has a perm of 600?

**Comment by mattt416** [comment]
I'd like to test this again end-to-end but generally this is looking fine to me. :+1:

**Comment by andymcc** [comment]
LGTM.

**Comment by hughsaunders** [comment]
LGTM. #ohwait

**Pull request merged**
